### PR TITLE
Update socket.dart

### PR DESCRIPTION
**Pull request by carlosmobile**
Hello,

First of all thanks for your great work in this library.

Please, could you make channel parameters more flexible and update de String, String to String, dynamic?

I need this change to use this library in our app. I think is a simple change that not affect negatively to any library user.

### CODE REVIEW

**Comment by matehat** [comment]
@carlosmobile Sure! I think this was a mistake from me. That needed to support JSON-serializable objects so your type definition reflects that better.

Thanks for the your contribution!

**Comment by matehat** [comment]
Published in 0.4.7 !

**Comment by carlosmobile** [comment]
Amazing @matehat !!

**Comment by carlosmobile** [comment]
We need to change in fromsocket too, sorry.

I/flutter (10251): Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>'
I/flutter (10251): #0      PhoenixSocket.addChannel (package:phoenix_socket/src/socket.dart:335:21)

**Pull request merged**
