### PR TITLE
Fix: correct usage of channels map

### PR DESCRIPTION
**Pull request by itxtoledo**
I noticed that the map channels comment says:

```
 /// [Map] of topic names to [PhoenixChannel] instances being
 /// maintained and tracked by the socket.
```

But what we see before this PR is a numerical reference to channels. This PR fixes this.

As a bonus we were able to reduce the time complexity to add new channel from O(n) to O(1)

### CODE REVIEW

**Comment by MapperMalte** [comment]
Awesome! I noticed it, too, when looking at the code and opened up this: https://github.com/braverhealth/phoenix-socket-dart/issues/58 which relates to this.

**Comment by matehat** [comment]
Great! Do you mind rebasing on main so we can run the CI check on it?

Thanks!

**Review by AugustoResende — APPROVED** [review]

**Comment by itxtoledo** [comment]
hey @matehat, are u okay?

**Comment by itxtoledo** [comment]
Will we ever see this PR merged? @matehat @phildupuis

**Comment by RodolfoSilva** [comment]
Hello guys.

Will this PR merged? @matehat @phildupuis ?

**Pull request merged**
